// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Grade struct {
	ID        int64        `json:"id"`
	StudentID int64        `json:"student_id"`
	Grade     int64        `json:"grade"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Student struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Number    int64        `json:"number"`
	Nation    string       `json:"nation"`
	CreatedAt sql.NullTime `json:"created_at"`
}
