// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	GetGrade(ctx context.Context, id int64) (Grade, error)
	GetGradeByStudentID(ctx context.Context, studentID int64) (Grade, error)
	GetGradeForUpdate(ctx context.Context, id int64) (Grade, error)
	GetStudent(ctx context.Context, id int64) (Student, error)
	GetStudentForUpdate(ctx context.Context, id int64) (Student, error)
}

var _ Querier = (*Queries)(nil)
