# Have a look at : https://dev.to/techschoolguru/how-to-setup-github-actions-for-go-postgres-to-run-automated-tests-81o
name: build-and-test

on:
  push:
    branches: [ main ]


jobs:
  # Job1
  build-and-test:
    name : build-and-test
    # runner declaration
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: nimda
          POSTGRES_DB: automation
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step1
    - name: Set up Go 1.x into the runner
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

      # Step2
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        command -V migrate

    # Step
    - name: Run migrations
      run: make create-schema
      
      # Step3
    - name: Get dependencies
      run: go get -v -t -d ./...

      # Step4
    - name: Build
      run: go build -v ./...

      # Step5
    - name: Test
      run: go test -v ./...